on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm install
            - name: Make stable release to npm
              uses: ./.github/actions/npm-release
              with:
                  token: ${{ secrets.CAZOO_NPM_TOKEN }}
